import * as THREE from 'three';
import * as CANNON from 'cannon-es';

const app=document.querySelector('#app');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x08100d);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100); camera.position.set(5,3.5,7); camera.lookAt(0,.7,0);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; app.append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xbaffd0,0x142018,2)); const sun=new THREE.DirectionalLight(0xffffff,3); sun.position.set(4,8,5); sun.castShadow=true; scene.add(sun);
const world=new CANNON.World({gravity:new CANNON.Vec3(0,-9.82,0)}); world.solver.iterations=14;
const mat=new CANNON.Material('grippy'); const contact=new CANNON.ContactMaterial(mat,mat,{friction:.85,restitution:.05}); world.addContactMaterial(contact);
const floorB=new CANNON.Body({mass:0,shape:new CANNON.Plane(),material:mat}); floorB.quaternion.setFromEuler(-Math.PI/2,0,0); world.addBody(floorB);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x183024,roughness:1})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor); scene.add(new THREE.GridHelper(30,30,0x356247,0x183a28));
const links=[]; function box(name,size,pos,mass,color){const body=new CANNON.Body({mass,shape:new CANNON.Box(new CANNON.Vec3(...size.map(v=>v/2))),position:new CANNON.Vec3(...pos),material:mat}); world.addBody(body); const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),new THREE.MeshStandardMaterial({color,roughness:.7})); mesh.castShadow=true; scene.add(mesh); links.push({name,body,mesh}); return body;}
const torso=box('torso',[2.2,.55,1.25],[0,1.35,0],5.5,0x54c77a);
const anchors=[[-.82,0,-.46],[-.82,0,.46],[0,0,-.55],[0,0,.55],[.82,0,-.46],[.82,0,.46]];
const legs=[];
for(let i=0;i<6;i++){const [x,,z]=anchors[i]; const side=Math.sign(z); const upper=box(`leg${i}-upper`,[.18,.18,.9],[x,1.05,z+side*.72],.35,0xa8d6b5); const lower=box(`leg${i}-lower`,[.16,.65,.16],[x,.67,z+side*1.12],.3,0x8ab89a); const hip=new CANNON.HingeConstraint(torso,upper,{pivotA:new CANNON.Vec3(x,-.12,z),axisA:new CANNON.Vec3(1,0,0),pivotB:new CANNON.Vec3(0,0,-side*.45),axisB:new CANNON.Vec3(1,0,0)}); const knee=new CANNON.HingeConstraint(upper,lower,{pivotA:new CANNON.Vec3(0,0,side*.45),axisA:new CANNON.Vec3(1,0,0),pivotB:new CANNON.Vec3(0,.325,0),axisB:new CANNON.Vec3(1,0,0)}); world.addConstraint(hip); world.addConstraint(knee); hip.enableMotor(); knee.enableMotor(); hip.setMotorMaxForce(7); knee.setMotorMaxForce(7); legs.push({hip,knee,phase:(i%3)*Math.PI*2/3 + (side>0?Math.PI:0)});}
let powered=true, gaitSpeed=2.2, effort=0; const hud=document.createElement('div'); hud.className='hud'; hud.innerHTML='<b>DIRTY DYNAMICS LAB v0.1</b><div>Six-leg articulated test body. This is physics, not an animation.</div><div><button id="power">Motors: ON</button><button id="kick">Shove body</button><button id="slow">Slow</button><button id="fast">Fast</button></div><div class="row" id="telemetry"></div>'; document.body.append(hud);
power.onclick=()=>{powered=!powered; power.textContent=`Motors: ${powered?'ON':'OFF'}`}; kick.onclick=()=>torso.applyImpulse(new CANNON.Vec3(7,1,0),torso.position); slow.onclick=()=>gaitSpeed=1.2; fast.onclick=()=>gaitSpeed=3.4;
let t=0,last=performance.now(); function loop(now){requestAnimationFrame(loop); const dt=Math.min((now-last)/1000,.03); last=now; t+=dt; effort=0; for(const l of legs){const wave=Math.sin(t*gaitSpeed+l.phase); const kneeWave=Math.sin(t*gaitSpeed+l.phase+.8); l.hip.setMotorSpeed(powered?wave*2.4:0); l.knee.setMotorSpeed(powered?kneeWave*2.1:0); effort+=Math.abs(wave)+Math.abs(kneeWave);} world.step(1/120,dt,5); for(const x of links){x.mesh.position.copy(x.body.position); x.mesh.quaternion.copy(x.body.quaternion);} telemetry.textContent=`mass≈${links.reduce((s,x)=>s+x.body.mass,0).toFixed(1)} kg | height ${torso.position.y.toFixed(2)} m | speed ${torso.velocity.length().toFixed(2)} m/s | actuator effort ${effort.toFixed(1)} | contacts handled by cannon-es`; renderer.render(scene,camera);} requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
